second/homepage/urls.py
from . import views
from django.urls import path


app_name = "homepage"


urlpatterns = [
    path("", views.home, name="home"),
    path("about", views.about, name="about"),
    path("todo", views.todo.todo1, name="todo"),
    path("account", views.account, name="account"),
    path("add", views.add, name="add"),
    path("delete", views.todo.delete, name="delete")
]

second/second/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls")),
]

second/homepage/models.py
from django.db import models

# Create your models here.

second/homepage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

tasks = []

class users():
    def __init__(self, name):
        self.list = []
    

    

def filter(s):
    p = "'name': ['"
    p2 = "']}>"
    begin = s.find(p) + len(p)
    finish = s.find(p2)
    return(s[begin:finish])
def filter2(s):
    p = "'task': ['"
    p2 = "']}>"
    begin = s.find(p) + len(p)
    finish = s.find(p2)
    return(s[begin:finish])

def filter3(s):
    p = "'nbr': ['"
    p2 = "']}>"
    begin = s.find(p) + len(p)
    finish = s.find(p2)
    return(s[begin:finish])


def home(request):
    return render(request, "homepage/home.html")

def about(request):
    return render(request, "homepage/about.html")

class todo:

    def delete(request):

        if len(tasks) == 0:
            return render(request, "homepage/todo.html",{
            "task1": filter3(str(request.POST)),
            "tasks": tasks,
            })
        else:

            taskNbr = int(filter3(str(request.POST)))
            tasks.pop(taskNbr)

            return render(request, "homepage/todo.html",{
                 "task1": filter3(str(request.POST)),
                 "tasks": tasks,
            
             })

    def todo1(request):


        if request.method == 'POST':
         
            tasks.append(filter2(str(request.POST)))

            return render(request, "homepage/todo.html",{
                "task1": filter2(str(request.POST)),
                "tasks": tasks,
                
           
        })
        else:
            return render(request, "homepage/todo.html", {
                "task1": filter2(str(request.POST)),
                "tasks": tasks,
                
        
        })


def account(request):
    if request.method == 'POST':
        
        
    
       return render(request, "homepage/account.html",{
            "Name": filter(str(request.POST)), 
            "status": 1,
           
        })
    else:
        return render(request, "homepage/account.html", {
            "status":0,
        
        })


def add(request):

    return render(request, "homepage/add.html")

second/homepage/templates/homepage/about.html
{%extends "homepage/templates.html" %}

{%block load%}

{%load static%}

{%endblock%}
{%block head%}

<title>About</title>
<link rel="stylesheet" href="{% static 'homepage/styles_about.css'%}">


{%endblock%}
{%block body%}

<h1 id="PageTitle">About us.</h1>

<div class="titles">
    <div id="aboutFamily">The Salari family lives in West Vancouver BC CANADA. We are part French and part German. Our family lives all over the world in places like:
        <ul>
            <li>Moroni, Comores</li>
            <li>Paris, France</li>
            <li>Hambourg, Deutschland</li>
            <li>and Vancouver, Canada</li>
        </ul>
        We are pround of who we are and what we stand for.
    </div>
    <div id="presenting">The Salari family has 3 children, let's meet them!</div>
</div>

<div id="children">
    <div id="child">
        <img src="{% static '/homepage/Kiyan.jpeg' %}" alt="Kiyan" width="300px">
        Kiyan is the youngest of the Salari family. He recently turned 8 on June 4th. He attends Cousteau School, the French international school of vancouver.
    </div>
    <div id="child">
        <img src="{% static '/homepage/Inaya.JPG' %}" alt="Inaya" width="300px">
        Inaya is the middle girl. She keeps the order (sometimes) and loves reading. She will turn 11 on September 2nd. She attends the same school as Kiyan and her favorite show is Paw Patrol.
    </div>
    <div id="child">
        <img src="{% static '/homepage/Ihsan.JPG' %}" alt="Ihsan" width="300px">
        Ihsan is the eldest child in the Salari family. He has been alive for a whopping 14yrs and will turn 15 on December 3rd. He attends Mulgrave school and hopes to perhaps become a computer scientist. 
    </div>
    
</div>

{%endblock%}
   

second/homepage/templates/homepage/account.html
{%extends "homepage/templates.html" %}

{%block load%}

{%load static%}

{%endblock%}
{%block head%}

<title>My Account</title>
<link rel="stylesheet" href="{% static  'homepage/styles_account.css' %}">

{%endblock%}
{%block body%}

{% if status %}

    <h1 id="PageTitle">Hello, {{Name}}.</h1>

    <a href="{%url 'homepage:todo'%}"><button class="button">To do.</button></a>
    <a href="{%url 'homepage:add'%}"><button class="button">Add task.</button></a>

{% else%}
    <h1 id="PageTitle">You are not logged in.</h1>
{%endif%}





{%endblock%}
   

second/homepage/templates/homepage/add.html
{%extends "homepage/templates.html" %}

{%block load%}

{%load static%}

{%endblock%}
{%block head%}

<title>Add task</title>
<link rel="stylesheet" href="{% static  'homepage/styles_add.css' %}">

{%endblock%}
{%block body%}

<form action="{%url 'homepage:todo'%}" class="form" id="login" method="post">
    {%csrf_token%}
    <input type="text" name="task" id="task" placeholder="Task" autofocus="autofocus">
    <input type="submit" id="submit" value="Submit">
</form>


{%endblock%}

second/homepage/templates/homepage/debug.html
{%extends "homepage/templates.html" %}

{%block load%}

{%load static%}

{%endblock%}
{%block head%}

<title>Debug</title>
<link rel="stylesheet" href="{% static  'homepage/styles_.css' %}">

{%endblock%}
{%block body%}

<h1> {{debug}} </h1>

{%endblock%}
   

second/homepage/templates/homepage/home.html
{%extends "homepage/templates.html" %}

{%block load%}
{%load static%}
{%endblock%}

{%block head%}
<title>Salari Family</title>
<link rel="stylesheet" href="{% static  'homepage/styles_home.css' %}">
{%endblock%}
{%block body%}

<h1 id="PageTitle">Home.</h1>

<div id="logo">
    <img src="{%static 'homepage/salari.jpg'%}" alt="Salari">
</div>
{%endblock%}
   
        
 

second/homepage/templates/homepage/template_updated.html
{%extends "homepage/templates.html" %}

{%block load%}

{%load static%}

{%endblock%}
{%block head%}

<title></title>
<link rel="stylesheet" href="{% static  'homepage/styles_.css' %}">

{%endblock%}
{%block body%}


{%endblock%}
   

second/homepage/templates/homepage/templates.html
<!DOCTYPE html>
{%block load%}
{%load static%}
{%endblock%}
<html>
    <head>
        <link rel="stylesheet" href="{% static  'homepage/styles_menu.css' %}">
        {%block head%}
        {%endblock%}
    </head>
    <body>
        <div id="Menu">
            <a href="{% url 'homepage:home'%}"><button class="button">Home</button></a>
            <a href="{% url 'homepage:about'%}"><button class="button">About us</button></a>
            <label for="login">Login:</label>

            <form action="{%url 'homepage:account'%}" class="form" id="login" method="post">
                {%csrf_token%}
                <input type="text" name="name" id="name" placeholder="Name">
                <input type="submit" id="submit" value="login">
            </form>

       </div>
        {%block body%}
        {%endblock%}
    </body>
</html>

second/homepage/templates/homepage/todo.html
{%extends "homepage/templates.html" %}

{%block load%}

{%load static%}

{%endblock%}
{%block head%}

<title>Todo</title>
<link rel="stylesheet" href="{% static  'homepage/styles_todo.css' %}">

{%endblock%}
{%block body%}
<h1 id="PageTitle">To do.</h1>
<ul>
    {%for task in tasks%}
        <li>
            <div id="task_display">
                
                <form action="{%url 'homepage:delete'%}" method="post" >
                {%csrf_token%}
                    <h1>{{task}}
                         <input type="hidden" id="nbr" name="nbr"  value="{{forloop.counter0}}">
                         <input type="submit" class="delete" value="Delete">
                    </h1>
                </form>
             </div>
        </li>
    {%empty%}
        No tasks.
    {%endfor%}

</ul>
<a href="{% url 'homepage:add'%}"><button class="button">Add task</button></a>
{%endblock%}
   